# Generated by Django 6.0.5 on 2026-05-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
