# Generated by Django 6.0.5 on 2026-05-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_subgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
