# Generated by Django 6.0.5 on 2026-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='goal_attachments/'),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('long_term', 'Long-Term')], default='daily', max_length=10),
        ),
    ]
