# Generated by Django 6.0.5 on 2026-05-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goal_attachment_goal_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgoal',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
