# Generated by Django 6.0.5 on 2026-05-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_goal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
